### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by yoonspark** [TillRS/SUN_TopicModel#6]
I noticed that the CI is failing. It is perhaps due to the incorrect specification the test dependency space, which is named as `tests` in `pyproject.toml`:

https://github.com/TillRS/SUN_TopicModel/blob/a8dcc8a130574c14fc967b4b3536c1b7174f4e0a/pyproject.toml#L34

but referenced as `test` in `.github/workflows/ci.yml`: 

https://github.com/TillRS/SUN_TopicModel/blob/761fe21ec5c91b03a041aae075e98cf1a515ea34/.github/workflows/ci.yml#L30

You can change either to make both identical.

**Comment by TillRS** [comment]
thanks! I just found/fixed this through some trial and error.

**Comment by yoonspark** [comment]
Yeah, I just saw it - I could have waited!

**Comment by TillRS** [comment]
Nono, thanks for keeping an eye out and letting me know! :)
